/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package braco2l;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author marcio
 */
public class Tela extends javax.swing.JFrame {

    private ArrayList<Forma> rets = new ArrayList<>();
    private Retangulo chao = new Retangulo(1024, 50, 0, -500, 90, Color.black);
    private Retangulo base = new Retangulo(50, 50, 0, -20, +40, Color.GRAY);
    private Retangulo haste = new Retangulo(30, 50, 0, base.getX() + 10, base.getY() - 50, Color.MAGENTA);
    private Retangulo l1 = new Retangulo(200, 20, 0, haste.getX(), haste.getY(), Color.GREEN);
    private Junta j1 = new Junta(10, l1.x + 5, l1.y + 5, Color.BLUE);
    private Retangulo l2 = new Retangulo(200, 20, 0, l1.getX() + l1.getW() - 20, l1.getY(), Color.ORANGE);
    private Junta j2 = new Junta(10, l2.x + 5, l2.y + 5, Color.BLUE);
    private Junta pontV = new Junta(10, l2.x + l2.getW() + 5, l2.y + 5, Color.red);

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        rets.add(chao);
        rets.add(base);
        rets.add(haste);
        rets.add(l1);
        l1.getFormas().add(l2);
        rets.add(j1);
        rets.add(j2);
        rets.add(pontV);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPos = new javax.swing.JLabel();
        spnL1 = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spnL2 = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setResizable(false);

        lbPos.setText("jLabel1");

        spnL1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnL1StateChanged(evt);
            }
        });

        jLabel1.setText("Ângulo L1");

        jLabel2.setText("Ângulo L2");

        spnL2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnL2StateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(lbPos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnL1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spnL2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnL1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spnL2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(89, 89, 89)
                .addComponent(lbPos)
                .addContainerGap(159, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void spnL1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnL1StateChanged
        if ((int) spnL1.getValue() < 0) {
            spnL1.setValue(0);
        }
        if ((int) spnL1.getValue() > 180) {
            spnL1.setValue(180);
        }
        l1.setA(-(int) spnL1.getValue());
        repintar();

    }//GEN-LAST:event_spnL1StateChanged

    private void spnL2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnL2StateChanged
        l2.setA(-(int) spnL2.getValue());
        repintar();        // TODO add your handling code here:
    }//GEN-LAST:event_spnL2StateChanged

    public void repintar() {
        repaint();
        lbPos.repaint();
    }

    void drawRectangles(Graphics g) {

        Graphics2D g2d = (Graphics2D) g;


        for (Forma r : rets) {
            r.render(g2d);
        }
        double x1 =  Math.cos(Math.toRadians(l1.getA())) * l1.getW();
        double y1 =  Math.sin(Math.toRadians(l1.getA())) * l1.getW();

        //double x2 = Math.cos(Math.toRadians(l1.getA() + l2.getA())) * l2.getW() + x1;
        //double y2 = Math.sin(Math.toRadians(l1.getA() + l2.getA())) * l2.getW() + y1;

        int x2 = (int) (x1 +  (int) (Math.cos(Math.toRadians(l2.getA())) * l2.getW()));
        int y2 = (int) (y1 +  (int) (Math.sin(Math.toRadians(l2.getA())) * l2.getW()));
        //y2 += y1;

        lbPos.setText("(" + x2 + ", " + y2 + ")");
        g.drawRect((int) x2, (int) y2, 10, 10);

    }

    public void paint(Graphics g) {
        super.paint(g);
        g.translate(500, 500);
        drawRectangles(g);

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbPos;
    private javax.swing.JSpinner spnL1;
    private javax.swing.JSpinner spnL2;
    // End of variables declaration//GEN-END:variables
}
